# Generated by Django 2.2.17 on 2021-02-26 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='Pizza_topping',
            new_name='pizza_topping',
        ),
    ]
